enum LocalStorageKey {
  SELECTED_NETWORK_KEY = 'SELECTED_NETWORK_KEY',
  CURRENT_TC_ACCOUNT = 'CURRENT_TC_ACCOUNT',
  TRANSACTION_COUNT = 'TRANSACTION_COUNT',
  ADVANCE_USER = 'ADVANCE_USER',
  CONNECTED_SITE = 'CONNECTED_SITE',
}

export { LocalStorageKey };
