enum LocalStorageKey {
  SELECTED_NETWORK = 'SELECTED_NETWORK',
  NETWORK_LIST = 'NETWORK_LIST',
  CURRENT_TC_ACCOUNT = 'CURRENT_TC_ACCOUNT',
  TRANSACTION_COUNT = 'TRANSACTION_COUNT',
}

export { LocalStorageKey };
