enum LocalStorageKey {
  SELECTED_NETWORK_NAME = 'SELECTED_NETWORK_NAME',
  CURRENT_TC_ACCOUNT = 'CURRENT_TC_ACCOUNT',
  TRANSACTION_COUNT = 'TRANSACTION_COUNT',
  ADVANCE_NETWORK = 'ADVANCE_NETWORK',
}

export { LocalStorageKey };
